### ISSUE TITLE
0.0.1/treadmill returning 404

### ISSUE THREAD

**Issue by mimiflynn** [morganstanley/treadmill#103]
From the root README:

`wget https://github.com/Morgan-Stanley/treadmill/releases/download/0.0.1/treadmill -O /usr/bin/treadmill && chmod +x /usr/bin/treadmill` is returning a 404.

Attempting to install on Ubuntu 16.04.

Log below:

```
--2017-11-07 13:17:44--  https://github.com/Morgan-Stanley/treadmill/releases/download/0.0.1/treadmill
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-07 13:17:44 ERROR 404: Not Found.
```

**Comment by ebourgeois** [comment]
Currently master is woefully behind, we are in the process of merging from another upstream repo.
